### ISSUE TITLE
Hakijan tulee saada sähköposti nimityksen yhteydessä

### ISSUE THREAD

**Issue by HYYkopo** [ayystudentunion/hhj#1]
Kuten otsikossa lukee. Alla esimerkki:

Onnea, <nimi>!

Sinut on valittu <elin> <varsinaiseksi/varajäseneksi>.

<muutoksenhakuohje>

**Comment by JukkaKarvonen** [comment]
Nykytiedon mukaan ei tarpeellinen automatisoituna.
