### ISSUE TITLE
Ilmoittaminen valinnoista ja valitsematta jättämisestä

### ISSUE THREAD

**Issue by EliasLaitinen** [ayystudentunion/hhj#101]
Ilmoittaminen valinnoista ja valitsematta jättämisestä integroituna järjestelmään. Jonkunlainen linkki, mistä klikkaamalla aukeaisi vaikka sähköpostiohjelman uusi sähköposti, jossa vastaanottajana henkilö. Yksi viestipohja pitäisi olla valmiina varsinaiseksi jäseneksi valituille, yksi varalle valituille ja yksi valitsematta jääneille, mutta itse muokattavissa (tämän voi toki copypasteta manuaalisestikin). Ja jos mahdollista niin erillinen sähköposti jokaiselle yksittäiselle henkilölle riippumatta siitä mihin näistä kategorioista kuuluu, ei yhtä monen vastaanottajan massapostia kaikille.

Jos on liian monimutkainen toteuttaa niin sitten mennään edelleen totaalisella copypastella.

**Comment by JukkaKarvonen** [comment]
Toteutus käsin.
