### ISSUE TITLE
Kaverisi pääsee kirjautumaan omilla tunnuksillaan, mutta edellisen kirjautujan nimellä järjestelmään.

### ISSUE THREAD

**Issue by hpiitula** [ayystudentunion/hhj#114]
Bugi::
-Salli evästeet selaimessa, äläkä poista niitä
-Kirjaudu sisään omilla tunnuksilla
-Kirjaudu ulos
-Älä sulje selainta/ikkunaa
-Käske kaverisi kirjautua samalla koneella, selaimella ja ikkunalla sisään omilla tunnuksillaan

Lopputulos:
Kaverisi pääsee kirjautumaan omilla tunnuksillaan, mutta sinun nimelläsi järjestelmään.

Tämä toimi ainakin vuonna 2013, en tiedä onko sitä vielä korjattu. Selaimena oli silloinen versio Google Chromesta ja käyttöjärjestelmänä Windows 7 pro.

**Comment by JukkaKarvonen** [comment]
Shibbolethin ominaisuus, selainikkuna tulee aina sulkea kun lopetat käytön.
