### ISSUE TITLE
Kuittaus hakemuksen tulosta perille

### ISSUE THREAD

**Issue by betelgeuse** [ayystudentunion/hhj#41]
Janne Lardot:n mailista: "Tarvittaisiin sellainen ominaisuus, että hakemuksen jätettyään käyttäjä saisi jonkinlaisen kuittauksen siitä että hakemus on tullut perille. Pelkkä ”kiitos, hakemuksesi on vastaanotettu”-viesti riittäisi."

**Comment by JukkaKarvonen** [comment]
#113
