### ISSUE TITLE
Oman hakemuksen tarkistaminen

### ISSUE THREAD

**Issue by Vodkis** [ayystudentunion/hhj#92]
Hakijan tulisi voida tarkistaa oma hakemuksensa sen lähettämisen jälkeen.

**Comment by betelgeuse** [comment]
@Vodkis hoituuko tämä sitä kautta, että hakemuksen voi korvata uudella vai mitä tällä ajetaan takaa?

**Comment by JukkaKarvonen** [comment]
Sähköpostikuittaus, jossa on tiedot ajanee asian.
